### ISSUE TITLE
Add Teams pull request reminder bot

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/ticket-assister#12]
## Context

Ticket assister should have the reminder bot to help make sure.

## Tasks

> Requires someone with SecAdmin privileges, if I recall correctly

- [x] follow the second half of the guide at https://wiki.illinois.edu/wiki/display/SEC/MS+Teams+GitHub+Notifications

**Comment by tzturner** [comment]
We reopened #32 to test PR reminders changes.
https://github.com/techservicesillinois/ticket-assister/pull/32

**Comment by tzturner** [comment]
Reminders appear to be working. Closing this!
